import { PALETTECOLORS, THEMEGRAYCOLOR } from "./paletteColors";

export const THEMECOLORS = {
  light: {
    "text-primary": THEMEGRAYCOLOR.light["gray-900"],
    "text-primary_on-brand": PALETTECOLORS.white,
    "text-secondary": THEMEGRAYCOLOR.light["gray-700"],
    "text-secondary_on-hover": THEMEGRAYCOLOR.light["gray-800"],
    "text-secondary_on-brand": PALETTECOLORS["brand-200"],
    "text-white": PALETTECOLORS.white,
    "text-disabled": THEMEGRAYCOLOR.light["gray-500"],
    "text-placeholder": THEMEGRAYCOLOR.light["gray-500"],
    "text-brand-primary": PALETTECOLORS["brand-900"],
    "text-brand-secondary": PALETTECOLORS["brand-700"],
    "text-brand-secondary_on-hover": PALETTECOLORS["brand-800"],

    "border-primary": THEMEGRAYCOLOR.light["gray-300"],
    "border-secondary": THEMEGRAYCOLOR.light["gray-200"],
    "border-disabled": THEMEGRAYCOLOR.light["gray-300"],
    "border-brand": PALETTECOLORS["brand-500"],

    "fg-primary": THEMEGRAYCOLOR.light["gray-900"],
    "fg-secondary": THEMEGRAYCOLOR.light["gray-700"],
    "fg-white": PALETTECOLORS.white,
    "fg-brand-primary": PALETTECOLORS["brand-600"],
    "fg-brand-secondary": PALETTECOLORS["brand-500"],

    "bg-primary": PALETTECOLORS.white,
    "bg-primary-solid": THEMEGRAYCOLOR.light["gray-950"],
    "bg-primary_on-hover": THEMEGRAYCOLOR.light["gray-50"],
    "bg-secondary": THEMEGRAYCOLOR.light["gray-50"],
    "bg-secondary_on-hover": THEMEGRAYCOLOR.light["gray-100"],
    "bg-secondary-solid": THEMEGRAYCOLOR.light["gray-600"],
    "bg-brand-primary": PALETTECOLORS["brand-50"],
    "bg-brand-secondary": PALETTECOLORS["brand-100"],
  },
  dark: {
    "text-primary": THEMEGRAYCOLOR.light["gray-900"],
    "text-primary_on-brand": PALETTECOLORS.white,
    "text-secondary": THEMEGRAYCOLOR.light["gray-700"],
    "text-secondary_on-hover": THEMEGRAYCOLOR.light["gray-800"],
    "text-secondary_on-brand": PALETTECOLORS["brand-200"],
    "text-white": PALETTECOLORS.white,
    "text-disabled": THEMEGRAYCOLOR.light["gray-500"],
    "text-placeholder": THEMEGRAYCOLOR.light["gray-500"],
    "text-brand-primary": PALETTECOLORS["brand-900"],
    "text-brand-secondary": PALETTECOLORS["brand-700"],
    "text-brand-secondary_on-hover": PALETTECOLORS["brand-800"],

    "border-primary": THEMEGRAYCOLOR.light["gray-300"],
    "border-secondary": THEMEGRAYCOLOR.light["gray-200"],
    "border-disabled": THEMEGRAYCOLOR.light["gray-300"],
    "border-brand": PALETTECOLORS["brand-500"],

    "fg-primary": THEMEGRAYCOLOR.light["gray-900"],
    "fg-secondary": THEMEGRAYCOLOR.light["gray-700"],
    "fg-white": PALETTECOLORS.white,
    "fg-brand-primary": PALETTECOLORS["brand-600"],
    "fg-brand-secondary": PALETTECOLORS["brand-500"],

    "bg-primary": PALETTECOLORS.white,
    "bg-primary-solid": THEMEGRAYCOLOR.light["gray-950"],
    "bg-primary_on-hover": THEMEGRAYCOLOR.light["gray-50"],
    "bg-secondary": THEMEGRAYCOLOR.light["gray-50"],
    "bg-secondary_on-hover": THEMEGRAYCOLOR.light["gray-100"],
    "bg-secondary-solid": THEMEGRAYCOLOR.light["gray-600"],
    "bg-brand-primary": PALETTECOLORS["brand-50"],
    "bg-brand-secondary": PALETTECOLORS["brand-100"],
  },
};
